# Playground

Resources:
1. http://biopython.org/DIST/docs/tutorial/Tutorial.html

In [252]:
# Imports.
import numpy as np
import pandas as pd
from Bio import SeqIO
from Bio.Seq import Seq
from utility_functions import desc_df
from utility_functions import print_color

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [253]:
df_iupac_aa_code = pd.read_csv('../Data/__iupac_amino_acid_code.csv')
df_iupac_aa_code.set_index('code1letter', inplace=True, drop=True)
df_iupac_aa_code

            code3letter           name
code1letter
A                   Ala        Alanine
C                   Cys       Cysteine
D                   Asp  Aspartic Acid
E                   Glu  Glutamic Acid
F                   Phe  Phenylalanine
G                   Gly        Glycine
H                   His      Histidine
I                   Ile     Isoleucine
K                   Lys         Lysine
L                   Leu        Leucine
M                   Met     Methionine
N                   Asn     Asparagine
P                   Pro        Proline
Q                   Gln      Glutamine
R                   Arg       Arginine
S                   Ser         Serine
T                   Thr      Threonine
V                   Val         Valine
W                   Trp     Tryptophan
Y                   Tyr       Tyrosine

In [254]:
proteins = {"id":[], "name":[], "source":[], "plastic":[], "n_plastics":[], "aa_seq":[]}
for p_data in SeqIO.parse("../Data/__plasticdb_protein_sequences.fasta", "fasta"):
    p_id, name, source, plastic = p_data.id.lower().replace('-','_').split("||")
    aa_seq = p_data.seq
    proteins['id'].append(int(p_id))
    proteins['name'].append(name)
    proteins['source'].append(source)
    proteins['plastic'].append(plastic)
    proteins['n_plastics'].append(len(plastic.split("_")))
    proteins['aa_seq'].append(aa_seq)

In [255]:
df_proteins = pd.DataFrame(proteins)
df_proteins.set_index('id', drop=True, inplace=True)
df_proteins

,name,source,plastic,n_plastics,aa_seq
id,,,,,
1,phb_depolymerase,ralstonia_pickettii,phb_pha,2,"(M, K, H, P, Y, G, Y, R, W, H, W, L, Y, A, L, ..."
2,pha_depolymerase,pseudomonas_fluorescens,pho_pha,2,"(M, P, L, R, T, L, L, C, G, L, L, L, A, V, C, ..."
3,phb_depolymerase_a,paucimonas_lemoignei,phb_pha,2,"(M, R, N, T, L, K, A, A, F, K, L, G, V, I, S, ..."
4,phb_depolymerase,paucimonas_lemoignei,phb_pha,2,"(M, L, A, K, Q, I, K, K, A, N, S, R, S, T, L, ..."
5,pha_depolymerase_b,paucimonas_lemoignei,phb_pha,2,"(M, M, S, S, Q, T, T, Q, S, S, K, F, S, L, F, ..."
...,...,...,...,...,...
204,petase,thermobifida_fusca,pet,1,"(M, A, A, N, P, Y, E, R, G, P, N, P, T, D, A, ..."
205,petase,thermobifida_alba,pet,1,"(M, A, N, P, Y, E, R, G, P, N, P, T, E, S, M, ..."
206,petase,thermobifida_cellulosilytica,pet,1,"(M, A, N, P, Y, E, R, G, P, D, P, T, Q, A, S, ..."
207,petase,thermobifida_halotolerans,pet,1,"(M, A, N, P, Y, E, R, G, P, N, P, T, N, S, S, ..."
208,petase,thermobifida_cellulosilytica,pet,1,"(M, A, N, P, Y, E, R, G, P, N, P, T, D, A, L, ..."

In [256]:
vc = df_proteins['aa_seq'].value_counts()
print(len(vc))
print(vc)

197
aa_seq
(M, A, V, M, T, P, R, R, E, R, S, S, L, L, S, R, A, L, Q, V, T, A, A, A, A, T, A, L, V, T, A, V, S, L, A, A, P, A, H, A, A, N, P, Y, E, R, G, P, N, P, T, D, A, L, L, E, A, S, S, G, P, F, S, V, S, E, E, N, V, S, R, L, S, A, S, G, F, G, G, G, T, I, Y, Y, P, R, E, N, N, T, Y, G, A, V, A, I, S, P, G, Y, ...)    3
(M, R, S, I, R, L, K, R, L, I, A, A, V, A, L, G, G, A, A, A, A, T, Q, A, A, S, P, L, P, R, L, N, V, D, K, T, Q, I, S, V, S, G, L, S, A, G, G, F, M, A, N, Q, L, G, Y, A, Y, S, G, T, F, M, G, V, G, I, F, A, G, G, P, Y, M, C, A, G, H, S, N, Y, T, S, C, M, Y, N, A, T, I, T, S, S, M, R, S, A, M, Q, A, S, ...)    3
(M, G, V, F, D, Y, K, N, F, T, A, S, D, S, K, A, L, F, S, D, A, L, A, I, T, L, Y, S, Y, H, N, I, D, N, G, F, A, E, G, Y, Q, H, N, G, F, G, L, G, L, P, A, T, L, V, T, A, L, I, G, S, G, N, S, Q, G, V, I, P, G, I, P, W, N, P, D, S, E, K, A, A, L, D, A, L, H, Q, A, G, W, S, T, I, S, A, Q, Q, L, G, Y, D, ...)    2
(M, N, F, P, R, A, S, R, L, M, Q, A, A, V, L, G, G, L, M, A, V, S, A, A, A, T, A, Q, T, N, P, Y, A, R, G, P, N, P, T, A, A, S, L, E, A, S, A, G, P, F, T, V, R, S, F, T, V, S, R, P, S, G, Y, G, A, G, T, V, Y, Y, P, T, N, A, G, G, T, V, G, A, I, A, I, V, P, G, Y, T, A, R, Q, S, S, I, K, W, W, G, P, R, ...)    2
(M, R, G, V, W, R, Y, M, P, V, Y, Y, Y, K, C, M, L, I, P, L, L, T, F, T, K, I, S, I, I, S, K, P, Q, E, S, R, I, S, L, I, I, C, R, T, M, P, T, V, A, T, F, L, G, L, A, I, S, G, A, A, M, A, S, G, A, A, L, G, A, Y, N, V, D, P, N, S, I, S, V, S, G, L, S, S, G, G, F, M, S, A, Q, L, G, V, A, Y, S, D, T, F, ...)    2
                                                                                                                                                                                                                                                                                                                    ..
(M, K, K, V, I, V, F, L, V, F, M, L, F, C, T, A, T, Y, A, Q, K, V, S, K, V, V, F, F, G, D, S, L, T, D, N, G, N, L, F, R, L, V, E, L, I, P, K, T, P, P, Y, Y, Q, G, R, F, S, N, G, P, T, W, A, E, N, L, G, E, Y, F, V, K, T, N, G, A, K, Y, E, I, Y, A, Y, A, G, A, T, A, A, A, H, N, I, F, E, T, L, A, P, T, ...)    1
(M, N, E, A, M, I, R, G, V, L, E, E, A, V, A, S, G, G, I, A, G, A, V, V, T, V, T, D, A, N, A, T, L, F, Q, L, A, V, G, R, Q, S, V, A, A, P, D, P, M, R, A, D, S, V, F, W, I, A, S, M, T, K, A, I, T, T, V, A, A, L, Q, L, V, E, Q, G, K, L, T, L, D, E, P, I, G, D, V, L, P, E, L, A, E, P, V, V, L, K, G, F, ...)    1
(M, R, T, V, D, G, R, I, G, M, V, E, R, R, T, R, L, V, S, L, L, A, A, A, A, L, A, V, S, L, S, G, C, S, A, T, T, V, L, N, T, L, E, P, R, W, D, V, A, A, T, R, D, V, A, Y, A, P, G, P, R, H, D, V, D, V, Y, A, P, K, K, I, G, P, H, T, P, V, V, V, F, I, Y, G, G, G, W, D, S, G, E, K, S, K, Y, A, F, V, G, S, ...)    1
(M, T, T, R, P, E, S, L, G, L, S, A, E, R, L, K, R, L, D, A, H, F, D, A, K, Y, V, Q, T, G, K, L, P, F, A, M, T, L, V, S, R, K, G, E, V, A, H, H, G, F, S, G, L, M, D, E, A, R, G, K, K, V, E, A, D, S, L, F, R, I, Y, S, M, T, K, P, L, T, S, V, L, F, M, M, L, V, E, E, G, K, V, A, L, D, D, P, V, H, S, L, ...)    1
(M, A, N, P, Y, E, R, G, P, N, P, T, D, A, L, L, E, A, R, S, G, P, F, S, V, S, E, E, N, V, S, R, F, G, A, D, G, F, G, G, G, T, I, Y, Y, P, R, E, N, N, T, Y, G, A, V, A, I, S, P, G, Y, T, G, T, Q, A, S, V, A, W, L, G, E, R, I, A, S, H, G, F, V, V, I, T, I, D, T, N, T, T, L, D, Q, P, D, S, R, A, R, Q, ...)    1
Name: count, Length: 197, dtype: int64

In [257]:
min(df_proteins['aa_seq'].apply(len)), max(df_proteins['aa_seq'].apply(len))

(108, 914)

In [258]:
df_microbes = pd.read_csv('../Data/__plasticdb_microbes.tsv', delimiter='\t')
desc_df(df_microbes)

No. of rows = 1701
No. of columns = 22

Feature Overview
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1701 entries, 0 to 1700
Data columns (total 22 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Microorganism                         1701 non-null   object
 1   Tax ID                                1701 non-null   int64
 2   Plastic                               1701 non-null   object
 3   Ref                                   1701 non-null   object
 4   Enzyme                                1654 non-null   object
 5   Enzyme ID                             384 non-null    float64
 6   Database Enzyne Name                  384 non-null    object
 7   Gene                                  1691 non-null   object
 8   GenbankID                             320 non-null    object
 9   Sequence                              384 non-null    object
 10  Year                                  1700 non-null   float64
 11  Evidence                              1656 non-null   object
 12  Plastic used                          1574 non-null   object
 13  Manufacturer                          1232 non-null   object
 14  Analitical grade                      949 non-null    object
 15  Thermophilic conditions               1647 non-null   object
 16  Isolation sample type                 1211 non-null   object
 17  Isolation environment                 1265 non-null   object
 18  Isolation location                    1048 non-null   object
 19  Degradation extrapolated from enzyme  1696 non-null   object
 20  Paper id                              24 non-null     object
 21  lineage                               1701 non-null   object
dtypes: float64(2), int64(1), object(19)
memory usage: 292.5+ KB
None

Value Counts

Microorganism
Uncultured bacterium           57
Streptomyces sp.               42
Aspergillus niger              40
Pseudomonas sp.                38
Bacillus sp.                   27
                               ..
Saccharothrix cryophilis        1
Saccharothrix coeruleofusca     1
Saccharothrix australiensis     1
Rhodotorula sphaerocarpa        1
Saccharopolyspora flava         1
Name: count, Length: 614, dtype: int64
No. of distinct values = 614
No. of missing values = 0

Tax ID
77133    57
1931     43
5061     40
306      38
1409     28
         ..
5078      1
69773     1
63821     1
63820     1
95161     1
Name: count, Length: 586, dtype: int64
No. of distinct values = 586
No. of missing values = 0

Plastic
PU              309
PHB             212
PCL             162
PLA             155
LDPE            145
               ...
Treated-HDPE      1
PLA Blend         1
PCL Blend         1
PBS Blend         1
PU Blend          1
Name: count, Length: 64, dtype: int64
No. of distinct values = 64
No. of missing values = 0

Ref
Navarro, D., Chaduli, D., Taussac, S., Lesage-Meessen, L., Grisel, S., Haon, M., ... & Favel, A. (2021). Large-scale phenotyping of 1,000 fungal strains for the degradation of non-natural, industrial compounds.                                                                                                                 220
Jeszeová, L., Puškárová, A., Bučková, M., Kraková, L., Grivalský, T., Danko, M., ... & Pangallo, D. (2018). Microbial communities responsible for the degradation of poly (lactic acid)/poly (3-hydroxybutyrate) blend mulches in soil burial respirometric tests. World Journal of Microbiology and Biotechnology, 34(7), 101.     52
Suyama, T., Tokiwa, Y., Ouichanpagdee, P., Kanagawa, T., & Kamagata, Y. (1998). Phylogenetic affiliation of soil bacteria that degrade aliphatic polyesters available commercially as biodegradable plastics. Appl. Environ. Microbiol., 64(12), 5008-5011.                                                                         38
Pranamuda, H., & Tokiwa, Y. (1999). Degradation of poly (L-lactide) by strains belonging to genus Amycolatopsis. Biotechnology Letters, 21(10), 901-905.                                                                                                                                                                            37
Gangoiti, J., Santos, M., Prieto, M. A., de la Mata, I., Serra, J. L., & Llama, M. J. (2012). Characterization of a novel subgroup of extracellular medium-chain-length polyhydroxyalkanoate depolymerases from actinobacteria. Appl. Environ. Microbiol., 78(20), 7229-7237.                                                       33
                                                                                                                                                                                                                                                                                                                                  ...
Watanabe, T., Ohtake, Y., Asabe, H., Murakami, N., & Furukawa, M. (2009). Biodegradability and degrading microbes of low‐density polyethylene. Journal of applied polymer science, 111(1), 551-559.                                                                                                                                  1
Jarerat, A., & Tokiwa, Y. (2003). Poly (L-lactide) degradation by Saccharothrix waywayandensis. Biotechnology letters, 25(5), 401-404.                                                                                                                                                                                               1
Volke‐Sepúlveda, T., Saucedo‐Castañeda, G., Gutiérrez‐Rojas, M., Manzur, A., & Favela‐Torres, E. (2002). Thermally treated low density polyethylene biodegradation by Penicillium pinophilum and Aspergillus niger. Journal of Applied Polymer Science, 83(2), 305-314.                                                              1
Azeko, S. T., Etuk-Udo, G. A., Odusanya, O. S., Malatesta, K., Anuku, N., & Soboyejo, W. O. (2015). Biodegradation of linear low density polyethylene by Serratia marcescens subsp. marcescens and its cell free extracts. Waste and biomass valorization, 6(6), 1047-1057.                                                          1
Skariyachan, S., Megha, M., Kini, M. N., Mukund, K. M., Rizvi, A., & Vasist, K. (2015). Selection and screening of microbial consortia for efficient and ecofriendly degradation of plastic garbage collected from urban and rural areas of Bangalore, India. Environmental monitoring and assessment, 187(1), 4174.                 1
Name: count, Length: 473, dtype: int64
No. of distinct values = 473
No. of missing values = 0

Enzyme
No                        1200
PHB depolymerase            82
Cutinase                    68
Esterase                    45
Hydrolase                   35
                          ...
Alkane-1 monooxygenase       1
Polyurethanase A             1
Polyurethanase B             1
MHETase                      1
Polyamidase                  1
Name: count, Length: 61, dtype: int64
No. of distinct values = 61
No. of missing values = 47

Enzyme ID
124.0    9
76.0     8
74.0     8
47.0     7
49.0     7
        ..
106.0    1
107.0    1
108.0    1
109.0    1
208.0    1
Name: count, Length: 208, dtype: int64
No. of distinct values = 208
No. of missing values = 1317

Database Enzyne Name
00124 | Polyester hydrolase | Moraxella sp. | PET PCL PU PHB PBS PLA PHA            9
00076 | Cutinase | Saccharomonospora viridis | PBAT PBS PBSA PCL PET PHB PLA PHA    8
00074 | Cutinase | Saccharomonospora viridis | PBAT PBS PBSA PCL PET PHB PLA PHA    8
00047 | PLA depolymerase | Uncultured bacterium | PLA PBS PBSA PCL PES PHB PHA      7
00049 | PLA depolymerase | Uncultured bacterium | PBS PBSA PCL PES PHB PLA PHA      7
                                                                                   ..
00106 | Cutinase | Thermobifida fusca | PET                                         1
00107 | Cutinase | Thermobifida alba | PET                                          1
00108 | Serine hydrolase | Thermobifida halotolerans | PET                          1
00109 | Triacylglycerol lipase | Polyangium brachysporum | PET                      1
00208 | PETase | Thermobifida cellulosilytica | PET                                 1
Name: count, Length: 208, dtype: int64
No. of distinct values = 208
No. of missing values = 1317

Gene
No     1307
Yes     384
Name: count, dtype: int64
No. of distinct values = 2
No. of missing values = 10

GenbankID
P19833        9
BAA19791.1    8
BAO42836.1    8
BAF57210.1    7
Q0VLQ1        6
             ..
P41365        1
AAA33335.1    1
A0A075B5G4    1
2FX5_A        1
ADV92525.1    1
Name: count, Length: 162, dtype: int64
No. of distinct values = 162
No. of missing values = 1381

Sequence
MRIRRQAGTGARASMARAIGVMTTALAVLVGAVGGVAGAEVSTAQDNPYERGPDPTEDSIEAIRGPFSVATERVSSFASGFGGGTIYYPRETDEGTFGAVAVAPGFTASQGSMSWYGERVASQGFIVFTIDTNTRLDQPGQRGRQLLAALDYLVERSDRKVRERLDPNRLAVMGHSMGGGGSLEATVMRPSLKASIPLTPWNLDKTWGQVQVPTFIIGAELDTIASVRTHAKPFYESLPSSLPKAYMELDGATHFAPNIPNTTIAKYVISWLKRFVDEDTRYSQFLCPNPTDRAIEEYRSTCPY                                                                                                                                                                                                  16
MFIMIKKSELAKAIIVTGALVFSIPTLAEVTLSETTVSSIKSEATVSSTKKALPATPSDCIADSKITAVALSDTRDNGPFSIRTKRISRQSAKGFGGGTIHYPTNASGCGLLGAIAVVPGYVSYENSIKWWGPRLASWGFVVITINTNSIYDDPDSRAAQLNAALDNMIADDTVGSMIDPKRLGAIGWSMGGGGALKLATERSTVRAIMPLAPYHDKSYGEVKTPTLVIACEDDRIAETKKYANAFYKNAIGPKMKVEVNNGSHFCPSYRFNEILLSKPGIAWMQRYINNDTRFDKFLCANENYSKSPRISAYDYKDCP                                                                                                                                                                                    9
MAFNFIRAAAAGAAMALCGVGSVHAAVNLPALKIDKTQTTVSGLSSGGFMAVQLHVAYSATFAKGAGVVAGGPFYCAEGSIVNATGRCMASPAGIPTSTLVSTTNTWASQGVIDPVANLQNSKVYLFSGTLDSVVKTGVMDALRTYYNSFVPAANVVYKKDIAAEHAMVTDDYGNACSTKGAPYISDCNFDLAGAMLQHLYGTLNARNNATLPTGNYIEFNQSEFITNHGMATTGWAYVPQACQAGGTATCKLHVVLHGCKQNIGDVQQQYVRNTGYNRWADTNNIVMLYPQTSTAATNSCWDWWGYDSANYSKKSGPQMAAIKAMVDRVSSGTGGTTPPDPVALPAPTGVSTSGATASSMAIGWAAVMGAASYNVYRNANKVNALPVTATSYTDTGLAASTTYSWTVRAADANGAEGATSAAASGTTLAASGGGTATCTTASNYAHTLAGRAYAAGGYTYALGSNQNMGLWNVFVTNTLKQTSTNYYVIGTCP     8
MRGVWRYMPVYYYKCMLIPLLTFTKISIISKPQESRISLIICRTMPTVATFLGLAISGAAMASGAALGAYNVDPNSISVSGLSSGGFMSAQLGVAYSDTFKVGFGVFAGGPYDCARGQSYTTCMYNQNPSITTPVANMKSWSGNKINPVSNLQSRKIYMWTGTADTTVGPNVMSQLKTQLANFASAANVSYITTSGAAHTFPTDFDAAGDNSCSSSVSPYISNCQCDGAGAVLQWMYGPLNARNPGTLSGSIVSFSQTGEYGASGMDTTGYLYVPRACQPGSSTVCKLHVALHGCKQSYSMIGSKFVSNTGYNMWADTNDIIILYPQAVADNTMHTIWTGMPLPNPNGCWDWVGWYGANADQVGGVQMAAIVNQVARVVSGYGAGSSSSTTAATPTTTTGSITTTTTTTATVTTTAVAPLYGQCGGIGWTGPTACATGVCTAYSPYYAQCLLIV                                             7
MLLKKRWLIFISFLLAFTLLIPTAASASEKHYKPNIALEPIENSEGNEHPIILVHGLGGFGRDELGGIIKMWGGIHDIEKKLREKGYKVYTAAVGPVSSNRDRAIELYYQIKGGTVDYGEAHAKKYGHDRYGRTYPGFYPEWGEINPKTGKPNKVHLIGHSMGGQTIRTLAQLLYEGDPEEHKTGGNDISPLLSGEKQPWLHSVLSISSPHDGSTATYLVNDVIPIIQELVIGAAIFAGNIDQNLYDFKLDHWGIKKRPGESFHSYVQRVRNSPGWKTKDTANWDLKPEGAYELNRWVKAQPDVYYFSVSNTQSRRSLLTGYYVPDLFMNPFLHPTAYYIGSKTFRKSNFVLDKTWWENDGLVSVKAMKGPNIGSNDVIVEYNGTPRKGVWNHLGTMRQFDHLDIIGWGVRDVTSWYEDVARFLYSLPDDY                                                                    7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ..
MTTRPESLGLSAERLKRLDAHFDAKYVQTGKLPFAMTLVSRKGEVAHHGFSGLMDEARGKKVEADSLFRIYSMTKPLTSVLFMMLVEEGKVALDDPVHSLIPSWKNLGVYAGGWDMMASKPCARPMQMVDLLRHTSGLTYGFQQRTNVDAAYRKHNIGVFERQISLDATIEALAALPLEFSPGEAWNYSVSTDILGYLIGKIEGRPFEEVLKARLTGPLGMDDTDFQVKASERGRFAACSAINAKGERVLNDDPEKSSYLQPPVLVSGGGGLVSTAGDYLKFCQMMLNGGEANGTRFLSPKTIALMTSNHLPGGVDLPQLSKSLFSEVAYDGVGFGLGFSVTMDPAKTLLPGTAGEYAWGGAASTAFWIDPKEELIVIFMTQLIPSSFYPIRRELRTLAYSAITESFV                                                                                           1
MRTVDGRIGMVERRTRLVSLLAAAALAVSLSGCSATTVLNTLEPRWDVAATRDVAYAPGPRHDVDVYAPKKIGPHTPVVVFIYGGGWDSGEKSKYAFVGSALASHGYLVFIPNYRIYPEAHYPDFLQDCALAVRWAKDHAAQYGGDPGELFLMGHSAGAYNAAMLATDPQWLGAVGMDPHRDLKGMVGLAGPYDFLPLQSDELKAIFGAVGQEPASQPINHVDGREPPMFLAHDLGDTVVYPKNTINMAAKIQAAGGEVETKYYKGLSHALMIGVFAAPLRFLGPVFRDSTQFIDAHASSSASKP                                                                                                                                                                                                  1
MNEAMIRGVLEEAVASGGIAGAVVTVTDANATLFQLAVGRQSVAAPDPMRADSVFWIASMTKAITTVAALQLVEQGKLTLDEPIGDVLPELAEPVVLKGFGADGAPVVEPAQAKLTLKHLLTHTSGFSYEFANGDLARYLERTGHPSAATGLKAGLRQPLMFEPGARWEYGIGIDWAGQAVEAASGMTLDAYFAAYVTGPLGMTDTLFLPRADQAARRVAMHQRQPDGSLTAVPFEPRPAPEYLAGGAGLYSTAPDYAAFLRMILNKGMGLLKPETVAAMGTNQIGALRAGKIGSVNPGLTAEADFYPGMDSKWGLGFLINPEKGSFGRSADSLTWAGLPNCYYWIDREKGIGAVILMQSLPSGDMGALKAAAGFEYALYASL                                                                                                                    1
MKKVIVFLVFMLFCTATYAQKVSKVVFFGDSLTDNGNLFRLVELIPKTPPYYQGRFSNGPTWAENLGEYFVKTNGAKYEIYAYAGATAAAHNIFETLAPTLLVDQVARYLETNPSDDKSKVLFVFWIGANDYLFLPTGNADELTTAAIQKTANGITTLLDQGAQNFLILDLPDLSKTPFAADLNMVSQMGSFTILHNQKLASLVDKMQKEHPQAQLMLFQLLQFSELIENPAKYNAKYHLNLSNTRAACWQGSVFDDIDTDNLANKTNKAISNPQPEVKEPILCEHPEQYVFFDHLHPTATVHQLLAALVEEAMNNRWS                                                                                                                                                                                    1
MANPYERGPNPTDALLEARSGPFSVSEENVSRFGADGFGGGTIYYPRENNTYGAVAISPGYTGTQASVAWLGERIASHGFVVITIDTNTTLDQPDSRARQLNAALDYMINDASSAVRSRIDSSRLAVMGHSMGGGGTLRLASQRPDLKAAIPLTPWHLNKNWSSVRVPTLIIGADLDTIAPVLTHARPFYNSLPTSISKAYLELDGATHFAPNIPNKIIGKYSVAWLKRFVDNDTRYTQFLCPGPRDGLFGEVEEYRSTCPFALELEHHHHHH                                                                                                                                                                                                                                  1
Name: count, Length: 199, dtype: int64
No. of distinct values = 199
No. of missing values = 1317

Year
2021.0    275
2018.0    171
2017.0    127
1999.0     81
2012.0     79
2022.0     78
2016.0     71
2014.0     54
2008.0     52
2011.0     50
1998.0     48
2015.0     45
2000.0     45
2019.0     45
2013.0     43
2010.0     41
2009.0     41
2004.0     40
2020.0     35
2003.0     30
2007.0     29
2005.0     27
2002.0     25
2006.0     23
1995.0     21
1997.0     18
2001.0     17
1996.0     16
1992.0     15
1991.0     12
1987.0     11
1994.0      9
1983.0      5
1993.0      5
1988.0      5
1990.0      3
1975.0      3
1986.0      2
1974.0      1
1977.0      1
1989.0      1
Name: count, dtype: int64
No. of distinct values = 41
No. of missing values = 1

Evidence
Clear zone                                474
Spectrophotometry                          55
CO2;Clear zone                             55
HPLC                                       55
Weight loss                                49
                                         ...
MS;Clear zone;SEM;Weight loss;              1
Clear zone;TOC;SEM                          1
GPC;FTIR                                    1
SEM;GPC;FTIR;Spectrophotometry;CO2;NMR      1
FTIR-ATR;NMR;SEM                            1
Name: count, Length: 296, dtype: int64
No. of distinct values = 296
No. of missing values = 45

Plastic used
Impranil                                                                                                                                                                                                                                                                                                                                                                                            247
PHB granules                                                                                                                                                                                                                                                                                                                                                                                         28
Amorphous PET film (Goodfellow Product ES30-FM-000145) and crystalline PET powder (Goodfellow Product ES30-PD-006031) were purchased from Goodfellow Corporation (USA).                                                                                                                                                                                                                              24
PLA granules                                                                                                                                                                                                                                                                                                                                                                                         24
Poly (3-hydroxybutric acid) (P(3HB) (Mn = 6.8 × 10^4, Mn/Mw = 2.6)                                                                                                                                                                                                                                                                                                                                   16
                                                                                                                                                                                                                                                                                                                                                                                                   ...
Aqueous PUR dispersion                                                                                                                                                                                                                                                                                                                                                                                1
PCL was prepared by ring opening polymerisation of E-caprolactone in benzene in a nitrogen atmosphere at 60 °C with a diethylzinc-water catalyst system.                                                                                                                                                                                                                                              1
High density PE                                                                                                                                                                                                                                                                                                                                                                                       1
Microbial cultures were cultivated in liquid nutrient medium devoid of carbon. The source of this element for the microor ganisms was sectioned HDPE polyethylene foil, the polymeric material comprising in its chemical structure only carbon and hydrogen in the form of unbranched hydrocarbon chain. The biological material was cultivated on solidified Luria- Bertani Broth (LB) medium.      1
Ecoflex is a commercial copolymer (BASF, Land Rheinland-Pfalz, Germany), which consists of 1,4-butanediol, adipic acid, and terephthalic acid                                                                                                                                                                                                                                                         1
Name: count, Length: 553, dtype: int64
No. of distinct values = 553

,Microorganism,Tax ID,Plastic,Ref,Enzyme,Enzyme ID,Database Enzyne Name,Gene,GenbankID,Sequence,...,Plastic used,Manufacturer,Analitical grade,Thermophilic conditions,Isolation sample type,Isolation environment,Isolation location,Degradation extrapolated from enzyme,Paper id,lineage
0,Ralstonia pickettii,329,PHB,"Yukawa, H., Uchida, Y., Kohama, K., & Kurusu, ...",PHB depolymerase,1.0,00001 | PHB depolymerase | Ralstonia pickettii...,Yes,BAA04986.1,MKHPYGYRWHWLYALVVTLMTALATFSAHAAVTAGPGAWSSQQTWA...,...,NaN,NaN,NaN,NaN,Soil,Soil,Japan,Yes,NaN,"superkingdom:Bacteria,phylum:Proteobacteria,cl..."
1,Ralstonia pickettii,329,PHA,"Yukawa, H., Uchida, Y., Kohama, K., & Kurusu, ...",PHB depolymerase,1.0,00001 | PHB depolymerase | Ralstonia pickettii...,Yes,BAA04986.1,MKHPYGYRWHWLYALVVTLMTALATFSAHAAVTAGPGAWSSQQTWA...,...,NaN,NaN,NaN,NaN,Soil,Soil,Japan,Yes,NaN,"superkingdom:Bacteria,phylum:Proteobacteria,cl..."
2,Pseudomonas fluorescens,294,PHO,"Schirmer, A., & Jendrossek, D. (1994). Molecul...",PHA depolymerase,2.0,00002 | PHA depolymerase | Pseudomonas fluores...,Yes,AAA64538.1,MPLRTLLCGLLLAVCLGQHALAASRCSERPRTLLRPAEVSCSYQST...,...,P(3HO) was isolated from P. oleovorans grown ...,NaN,Yes,No,NaN,NaN,NaN,Yes,NaN,"superkingdom:Bacteria,phylum:Proteobacteria,cl..."
3,Pseudomonas fluorescens,294,PHA,"Schirmer, A., & Jendrossek, D. (1994). Molecul...",PHA depolymerase,2.0,00002 | PHA depolymerase | Pseudomonas fluores...,Yes,AAA64538.1,MPLRTLLCGLLLAVCLGQHALAASRCSERPRTLLRPAEVSCSYQST...,...,P(3HO) was isolated from P. oleovorans grown ...,NaN,Yes,No,NaN,NaN,NaN,Yes,NaN,"superkingdom:Bacteria,phylum:Proteobacteria,cl..."
4,Paucimonas lemoignei,29443,PHB,"Jendrossek, D. I. E. T. E. R., Frisse, A. N. D...",PHB depolymerase A,3.0,00003 | PHB depolymerase-A | Paucimonas lemoig...,Yes,AAA65705.1,MRNTLKAAFKLGVISAALLAPFATQAATAGPGAWSSQQTWAADSVN...,...,The homopolyester PHB was isolated from sodium...,NaN,Yes,No,Culture collection,Culture collection,NaN,No,NaN,"superkingdom:Bacteria,phylum:Proteobacteria,cl..."

In [259]:
useful_features = ["Enzyme ID", 'Degradation extrapolated from enzyme']
df_microbes_useful = df_microbes[useful_features]
df_microbes_useful = df_microbes_useful[~df_microbes_useful['Enzyme ID'].isna()]
df_microbes_useful = df_microbes_useful[~df_microbes_useful['Degradation extrapolated from enzyme'].isna()]
df_microbes_useful

      Enzyme ID Degradation extrapolated from enzyme
0           1.0                                  Yes
1           1.0                                  Yes
2           2.0                                  Yes
3           2.0                                  Yes
4           3.0                                   No
...         ...                                  ...
1696      204.0                                  Yes
1697      205.0                                  Yes
1698      206.0                                  Yes
1699      207.0                                  Yes
1700      208.0                                  Yes

[379 rows x 2 columns]

In [260]:
enzyme_degradation = {}
for index, row in df_microbes_useful.iterrows():
    enzyme_id = row['Enzyme ID']
    degradation = int(row['Degradation extrapolated from enzyme'] == 'Yes')
    if (
        enzyme_id not in enzyme_degradation 
        or enzyme_id in enzyme_degradation 
        and enzyme_degradation[int(enzyme_id)] == 0
    ): enzyme_degradation[int(enzyme_id)] = degradation
enzyme_degradation = {
    "id": list(enzyme_degradation.keys()), 
    "degradation": list(enzyme_degradation.values())
}
df_enzyme_degradation = pd.DataFrame(enzyme_degradation)
df_enzyme_degradation.set_index('id', inplace=True, drop=True)
df_enzyme_degradation

     degradation
id
1              1
2              1
3              0
4              0
5              0
..           ...
204            1
205            1
206            1
207            1
208            1

[203 rows x 1 columns]

In [261]:
df_proteins = pd.concat(
    [df_proteins, df_enzyme_degradation],
    axis=1,
    join="outer",
    ignore_index=False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity=False,
    copy=True,
)
df_proteins

,name,source,plastic,n_plastics,aa_seq,degradation
id,,,,,,
1,phb_depolymerase,ralstonia_pickettii,phb_pha,2,"(M, K, H, P, Y, G, Y, R, W, H, W, L, Y, A, L, ...",1.0
2,pha_depolymerase,pseudomonas_fluorescens,pho_pha,2,"(M, P, L, R, T, L, L, C, G, L, L, L, A, V, C, ...",1.0
3,phb_depolymerase_a,paucimonas_lemoignei,phb_pha,2,"(M, R, N, T, L, K, A, A, F, K, L, G, V, I, S, ...",0.0
4,phb_depolymerase,paucimonas_lemoignei,phb_pha,2,"(M, L, A, K, Q, I, K, K, A, N, S, R, S, T, L, ...",0.0
5,pha_depolymerase_b,paucimonas_lemoignei,phb_pha,2,"(M, M, S, S, Q, T, T, Q, S, S, K, F, S, L, F, ...",0.0
...,...,...,...,...,...,...
204,petase,thermobifida_fusca,pet,1,"(M, A, A, N, P, Y, E, R, G, P, N, P, T, D, A, ...",1.0
205,petase,thermobifida_alba,pet,1,"(M, A, N, P, Y, E, R, G, P, N, P, T, E, S, M, ...",1.0
206,petase,thermobifida_cellulosilytica,pet,1,"(M, A, N, P, Y, E, R, G, P, D, P, T, Q, A, S, ...",1.0
207,petase,thermobifida_halotolerans,pet,1,"(M, A, N, P, Y, E, R, G, P, N, P, T, N, S, S, ...",1.0
208,petase,thermobifida_cellulosilytica,pet,1,"(M, A, N, P, Y, E, R, G, P, N, P, T, D, A, L, ...",1.0

In [262]:
df_proteins = df_proteins[df_proteins['degradation'] == 1].reset_index(drop=True)
df_proteins.drop('degradation', axis=1, inplace=True)
df_proteins

,name,source,plastic,n_plastics,aa_seq
0,phb_depolymerase,ralstonia_pickettii,phb_pha,2,"(M, K, H, P, Y, G, Y, R, W, H, W, L, Y, A, L, ..."
1,pha_depolymerase,pseudomonas_fluorescens,pho_pha,2,"(M, P, L, R, T, L, L, C, G, L, L, L, A, V, C, ..."
2,pva_dehydrogenase,pseudomonas_sp.,pva,1,"(M, Q, Q, N, I, E, R, N, Q, V, S, M, T, T, S, ..."
3,phb_depolymerase,comamonas_acidovorans,p3hp_p4hb_pea_pes_phb_pha,6,"(M, A, F, N, F, I, R, A, A, A, A, G, A, A, M, ..."
4,phb_depolymerase,comamonas_testosteroni,phb_pha,2,"(M, R, V, Q, S, W, R, S, G, V, A, A, L, A, L, ..."
...,...,...,...,...,...
116,petase,thermobifida_fusca,pet,1,"(M, A, A, N, P, Y, E, R, G, P, N, P, T, D, A, ..."
117,petase,thermobifida_alba,pet,1,"(M, A, N, P, Y, E, R, G, P, N, P, T, E, S, M, ..."
118,petase,thermobifida_cellulosilytica,pet,1,"(M, A, N, P, Y, E, R, G, P, D, P, T, Q, A, S, ..."
119,petase,thermobifida_halotolerans,pet,1,"(M, A, N, P, Y, E, R, G, P, N, P, T, N, S, S, ..."
120,petase,thermobifida_cellulosilytica,pet,1,"(M, A, N, P, Y, E, R, G, P, N, P, T, D, A, L, ..."

In [263]:
# df_proteins.to_csv('../Data/__plasticdb_protein_sequences_clean.csv', index=False)